language: node_js
node_js: node
dist: trusty
sudo: false

script:
 - wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
 - npm run build

before_deploy: 
- git fetch --tags
- npm run zip