language: node_js
node_js: node
dist: trusty
sudo: false

script:
 - wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('~/calibre-bin', True)"
 - npm run build

before_deploy: 
- git fetch --tags
- npm run zip